# Generated by Django 3.2.4 on 2021-06-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='titel',
            new_name='title',
        ),
    ]
